// content_types.cjs

const ContentTypes = {
	'.7z': 'application/x-7z-compressed',
	'.avi': 'video/x-msvideo',
	'.bin': 'application/octet-stream',
	'.bmp': 'image/bmp',
	'.c':'text/x-c',
	'.cc':'text/x-c',
	'.cjs': 'application/node',
	'.conf': 'text/plain',
	'.cpp':'text/x-c',
	'.css': 'text/css',
	'.csv': 'text/csv',
	'.dtd': 'application/xml-dtd',
	'.flv': 'video/x-flv',
	'.gif': 'image/gif',
	'.glb': 'model/gltf-binary',
	'.gltf': 'model/gltf+json',
	'.gz': 'application/gzip',
	'.h':'text/x-c',
	'.htm':'text/html',
	'.html':'text/html',
	'.ico': 'image/x-icon',
	'.importmap': 'application/importmap+json',
	'.jpg': 'image/jpeg',
	'.js': 'text/javascript',
	'.json': 'application/json',
	'.log': 'text/plain',
	'.m4u': 'video/vnd.mpegurl',
	'.mjs': 'text/javascript',
	'.mkv': 'video/x-matroska',
	'.mp3': 'audio/mpeg',
	'.mp4': 'video/mp4',
	'.mpeg': 'video/mpeg',
	'.mpg': 'video/mpeg',
	'.mtl': 'model/mtl',
	'.obj': 'model/obj',
	'.ogg': 'audio/ogg',
	'.ogv': 'video/ogg',
	'.pdf': 'application/pdf',
	'.png': 'image/png',
	'.py':'text/x-python',
	'.svg': 'image/svg+xml',
	'.tgz': 'application/gzip',
	'.txt': 'text/plain',
	'.wav': 'audio/wav',
	'.webm': 'video/webm',
	'.webp': 'image/webp',
	'.wmv': 'video/x-ms-wmv',
	'.woff': 'font/woff',
	'.woff2': 'font/woff2',
	'.xml': 'application/xml',
	'.xsl': 'application/xml',
	'.xslt': 'application/xslt+xml',
	'.zip': 'application/zip',
};
module.exports = ContentTypes;
